# Generated by Django 4.1.5 on 2023-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Студент?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Учитель?'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.SmallIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True, verbose_name='Оценка'),
        ),
    ]
